### ISSUE TITLE
循环生成 component

### ISSUE THREAD

**Issue by i-tengfei** [maichong/labrador-cli#4]
是否可以实现如下使用方法？

```
<scroll-view class="viewer">
    <block wx:for="childrens">
        <component key="{{item}}" />
    </block>
</scroll-view>
```

**Comment by liangxingchen** [comment]
很有必要的功能，我会尝试加上的

**Comment by i-tengfei** [comment]
因为比较着急使用，现在知道大概是在 https://github.com/maichong/labrador-cli/blob/master/lib/build-xml.js#L125 这个方法内修改，我想自己动手先实现了，之后再提 MR 合并过来，能大概介绍一下，如果我要实现这个功能，可能有哪些点需要注意的吗？

**Comment by liangxingchen** [comment]
如果模板循环的话，组件类中的children 对象也必须是一个数组，目前的机制是children 中的所有子组件是父组件初始化时就定好的，所以看似简单的问题，涉及比较多，不仅仅是改build-xml.js 就行的

**Comment by liangxingchen** [comment]
你能不能先用 `<template/>` 应急

**Comment by i-tengfei** [comment]
template有想过，但是不合适，template打破了labrador的组件链。

```
componentA:Title
    componentB:List
    componentC:Box
        componentD:Title
        componentE:List
            ....
```

这里是一个很深的组件树，而且树结构并不是固定的，而是根据不同的配置解析出来的，所以才会有了上面的需求。

谢谢回复，labrador确实是一个很不错的框架，提供了界面不变的情况下组件化的解决方案。

**Comment by liangxingchen** [comment]
你这个是不是需要组件递归调用了？

**Comment by i-tengfei** [comment]
是的，如果支持递归调用更好，但是不支持也可以规避。

**Comment by liangxingchen** [comment]
0.5版本已经实现了 [自定义组件列表](https://github.com/maichong/labrador#自定义组件列表)
